### ISSUE TITLE
Doing some extra checks when importing users

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/fas2ipa#18]
Discussed today with @abompard so creating issue here to track the request.
As we'll have also to migrate CentOS users (from the https://accounts.centos.org FAS instance), we should verify in case of name conflict that user from one side is indeed user from the other side.
Let's assume that we have `user1` existing in FAS and then we try to import CentOS Account, but that we also have user `user1` in FAS/IPA, we should verify/confirm that it's indeed same user before just adding existing user into groups that were also migrated.

There is indeed no nickname protection, so the only "primary key" to validate that same nickname is the same user is to validate that email address (validated on each side) is indeed the same, and if not, not do anything (not adding existing user in groups) but mark these in a "to be processed later" state.

From that report, we can reach out to users in such state and ask them to change/update their email address to match in both FAS and ACO and then put users into correct groups. If not, (and same nickname mismatch, aka same nickname for different users), we should discuss how to handle that, but probably just put new nickname in correct groups

**Comment by nphilipp** [comment]
Here we go (WIP): https://github.com/fedora-infra/fas2ipa/pull/20
