### ISSUE TITLE
User's fullname are not synced additively

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fas2ipa#24]
There's a case of a user with a fullname attribute in CentOS, but no fullname in FAS, that ends up with no firstname/lastname in IPA (they have the standard "unset" fillers). See user `carlwgeorge`. The fullname sync should be additive.

**Comment by nphilipp** [comment]
@abompard I'm not sure what additive means if the user has different real (not unset filler) names in both systems—I'd just retain what's in IPA and not change the name in this case.

That aside, detecting unset fillers and overwriting in this case shouldn't be hard.

**Comment by nphilipp** [comment]
> @abompard I'm not sure what additive means if the user has different real (not unset filler) names in both systems—I'd just retain what's in IPA and not change the name in this case.

Nah, I'll overwrite instead because it's easier :wink:—otherwise we'd have to retrieve info about the user from IPA.
